name: Update Sonolus JSON

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run update script
        run: python scripts/update_sonolus.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update Sonolus JSON" || exit 0
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
