name: Update Sonolus JSON

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  push:
    branches:
      - main  

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes
        run: git pull origin main  

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run the update script
        run: python scripts/update_sonolus.py

      - name: Commit and push changes
        run: |
          git add sonolus_data.json
          git commit -m "Auto-update Sonolus JSON" || echo "No changes to commit"  # Only commit if there are changes
          git push origin main  # Push changes back to the remote repository

